### ISSUE TITLE
Consider adding internal state using customElement

### ISSUE THREAD

**Issue by rchillard** [rchillard/fido#2]
From: https://www.keithcirkel.co.uk/css-classes-considered-harmful/

```javascript
customElements.define('my-card', class extends HTMLElement {
  #internal = this.attachInternals()
  
  async connectedCallback() {
    this.#internal.states.add('--loading')

    await fetchData()
	
    this.#internal.states.delete('--loading')
    this.#internal.states.add('--loaded')
  }
})
```

```css
my-card:--loading { background: url(./spinner.svg) }
my-card:--loaded { border: 2px solid green }
```

How does this impact style inheritance?
